name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (if needed for building your React app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the app
      - name: Build React App
        run: npm run build  # This assumes your build folder is created under `./build/`

      # Step 5: Deploy to Cloudflare Pages using the Cloudflare API
      - name: Deploy to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # Cloudflare API Token stored as a GitHub secret
          CF_SITE_ID: ${{ secrets.CF_SITE_ID }}      # Cloudflare Pages Site ID stored as a GitHub secret
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/sites/$CF_SITE_ID/deployments" \
          -H "Authorization: Bearer $CF_API_TOKEN" \
          -F "files[]=@./build/*"  # Deploy the contents of the 'build' folder to Cloudflare Pages
