name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Provision Web Server with Ansible
        run: |
          echo "Provisioning web server with Ansible..."
          # You can customize this with your Ansible commands, example:
          ansible-playbook -i ansible/hosts ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Install dependencies
        run: npm ci 

      - name: Build the app
        run: npm run build  

      - name: Check build directory
        run: |
          ls -l
          if [ ! -d "./dist" ]; then
            echo "Error: Build directory not found!"
            exit 1
          fi
 

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }} 
          projectName: "authentication-frontend" 
          directory: "./dist"
          branch: "main" 
          wranglerVersion: 2
              
