name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install Wrangler (Cloudflare CLI)
      - name: Install Wrangler
        run: npm install -g wrangler

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci  # Faster and more reliable than npm install

      # Step 5: Build the application
      - name: Build the app
        run: npm run build  

      # Step 6: Verify the build output
      - name: Check build directory
        run: |
          ls -l
          if [ ! -d "./dist" ]; then
            echo "Error: Build directory not found!"
            exit 1
          fi
      
      # - name: Install jq
      #   run: sudo apt-get install jq
      
      
      # - name: Get Cloudflare Account ID
      #   id: get_account_id
      #   run: |
      #     sudo apt-get install -y jq  # Ensure jq is installed
      #     ACCOUNT_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts" \
      #       -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
      #       -H "Content-Type: application/json" | jq -r '.result[0].id')
      
      #     if [ -z "$ACCOUNT_ID" ] || [ "$ACCOUNT_ID" == "null" ]; then
      #       echo "❌ Failed to fetch Cloudflare Account ID!"
      #       exit 1
      #     fi
      
      #     echo "✅ Cloudflare Account ID: $ACCOUNT_ID"
      #     echo "account_id=$ACCOUNT_ID" >> $GITHUB_ENV   


      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ env.account_id }}
          projectName: "testproject"
          directory: "./dist"
          branch: main
        
